# Discussion

## Plant development and soil coverage
In the mixed stands, NLL and oats displayed a marked convergence of phenological timing: Both crops reached maturity at nearly identical times, which facilitated the appropriate harvest timing. Such synchrony simplifies harvest logistics and has been identified as a key attribute explaining the high performance of cereal/legume mixed cropping systems [@demie2022]. Height measurements revealed only a transient effect of mixed cropping: Oats in mixed stands were slightly shorter than their monoculture counterparts in mid-May but no differences persisted in June and July, and NLL height remained unaffected throughout. Such height symmetry has been shown to be an architecture associated with superior mixture outcomes [@demie2022]. Because soil exposure to sun strongly influences soil evaporation, the more rapid soil coverage of the mixed treatments supported efficient water use and may have contributed to the positive protein yield responses reported, given the total precipitation was below the norm during this study [@yu2019]. Taken together, synchronised phenology, minor height differences, and superior canopy development constitute a coherent syndrome of compatibility that can largely be predicted from monoculture traits. Further, the absence of variety‑specific interactions across these attributes highlights the general compatibility of NLL with oats in mixed cropping.

## Plant health and weed pressure
The observed reduction in cereal leaf beetle incidence in mixed stands aligns with the principles of the dilution effect, wherein the presence of non-host or less susceptible species reduces pest pressure on the primary host crop [@civitello2015]. This phenomenon was evident in the present study; in one year, the significant reductions in cereal leaf beetle populations was even decisive that the threshold of interference was exceeded in pure stands of oats but not exceeded in mixed stands of the same oat variety. Previous research has documented that diversified cropping systems disrupt pest colonisation and feeding patterns, thereby mitigating pest impacts [@finch2000]. In the present study, mixed stands of oats and NLL effectively diluted the cereal leaf beetle population. Similar findings have been reported by @tooker2012,whose findings support the fact that increased plant diversity can impede pest movement and reduce localised pest aggregation. Thus, mixed cropping of NLL and oats is a viable approach to control cereal leaf beetle populations.

Mixed cropping also led to a substantial reduction of the weed pressure comparing pure with mixed NLL stands. Thus, especially in organic cultivation, where the application of herbicides is not allowed, mixed cropping provides an option to reduce the weed pressure in pulses [@trenbath1993; @verret2017; @pradhan2022]. The  mixed cropping system of NLL and oats in the present study led to a higher number of plants per square metre than the pure NLL stands (138 vs 120), however, this effect alone does most probably not explain the full reduction of the weed volumes by up to 83%. The observation of strongly reduced weed volumes in pure stands of oats, suggests that oats are the main cause. In fact, oats have a strong suppressing effect on other plants, including field mustard (*Sinapis arvensis*) [@kato-noguchi1994, @baghestani1999], which was one of the dominant weed species in the current study. This effect was attributed to the root exudates of the oat plants who’s strong allelopathic effects reduce the growth of other plants, which is in line with the lower weed pressure in pure oat stands than in mixed oat stand, where fewer oat plants exude allelopathic substances. Conversely, across both years and sites, mixed treatments with NLL had covered the soil earlier (closed canopy) than the pure oat stands, yet the earlier soil coverage was not accompanied by lower, but instead higher, weed pressure. Thus, irrespective of soil coverage development, the sowing of only 10% of oats in a replacement design led to a strong effect of the oat crop suppressing weeds despite a high weed pressure.

In the 2023 cultivation season at Reckenholz, the NLL crop exhibited chlorosis symptoms, which were associated with elevated levels of free calcium in the soil and the highest pH-value (7.0) of all fields (Table 2). This condition likely contributed to the observed reduction in NLL yield, as both, elevated free calcium and soil pH-values have been shown to induce chlorosis in NLL and reduce their growth [@ding2019]. This reduced viability of the NLL crop was also reflected in lower partial protein yield and LERs of the NLL in Reckenholz in 2023. Interestingly, despite the absence of visual symptoms, the NLL also exhibited lower performances of the site Reckenholz in 2022, which can again be linked to the elevated levels of free calcium and soil pH-values (6.9). These findings underscore the need for careful site selection to ensure high NLL productivity.

## Productivity and yield stability
The oat companion crop on the other hand showed the opposite development of yield to the NLL and exhibited elevated yield and higher pLERs at the site Reckenholz in both years. Additionally, the strong negative correlation between the NLL and oat yield substantiates the compensatory yield buffering of this mixed cropping system over pure stands. This finding is underlined by a study of  @raseduzzaman2017, which provided compelling evidence for the hypothesis that mixed cropping systems can enhance yield stability compared with pure stands. Although the rather high pH-values and the free calcium were adverse growing conditions for the NLL, the mixed cropping system buffered against this environmental variability, by utilising complementary plant interactions and resource use efficiency. In case of N fertilisation, this phenomenon was demonstrated in a review by @pelzer2014.  We thus suggest that the NLL-oat mixed crops’ resilience of the current study is due to the diversification of crops with complementary stress responses, leading to more stable aggregate yield.

Beyond the improved yield stability, Lunabor × Troll achieved an elevated LER. This gain in land use coincided with the strongest suppression of cereal leaf beetle in the oat crop and the smallest canopy-height asymmetry between the oat and NLL crop in the mixture. This suggests that reduced pest pressure together with a more balanced canopy mitigated asymmetric light competition and supported more efficient land use. Presumably, this elevated LER is thus owed to a above-average decrease in the pest pressure on oats resulting in a healthier crop, and the best growth dynamics between the observed oat and NLL varieties. Such improved productivity amongst identical plant-canopy architectures was previously reported [@maclaren2023].

## Crop quality
The capacity of pulses to fix atmospheric N, enables mixed cropped cereals to acquire a greater proportion of soil nitrogen (N), thereby enhancing their yield relative to pure stands [@hauggaard-nielsen2005]. In the present study, while NLL yield and protein yield were either maintained or slightly reduced in mixtures, the oat yield and protein yield consistently exceeded the expected values. This outcome can be attributed to the pulse's fixation of atmospheric N, reducing its reliance on soil N, and in turn effectively leaving more soil N available for the cereal partner [@jensen2020]. Although direct N transfer is limited, higher N availability for the cereals in mixture thanks to the N-sparing effect has been shown to benefit cereal growth [@hauggaard-nielsen2005]. Notably, NLL are known to fix even higher amounts of N in mixtures than in pure stands, further enhancing N availability for oats [@palmason1992]. The effect of the higher N availability is particularly evident by the observed elevated pLER and protein overyielding for oats in mixtures and further substantiated by consistently higher protein contents in all oat varieties in mixed stands across all mixtures, years, and sites.This effect for the cereal crop was previously also shown in a durum wheat-winter pea mixed crop [@bedoussac2010]. In the present study, since mixtures were not fertilised, the higher oat protein content and partial protein overyielding in mixtures are thus primarily attributable to the N-sparing effect. Specifically, the N-sparing effect in mixed stands exceeded the N-fertiliser effect in pure stands.

# Conclusion
The absence of a mixed cropping response of several other attributes, in particular agronomic traits including tiller number and plant height, underscores the potential for forecasting mixture performance based on monoculture data. Furthermore, the absence of specific variety effects for oats and NLL across these attributes supports the potential extrapolation onto other NLL and oat varieties. Still, to refine this approach, future studies should expand the range of tested varieties and sowing ratios to further substantiate the possibility to predict and optimise the mixed cropping performance based on pure stand metrics. This is particularly relevant given the importance of selecting mixtures with synchronised phenology to optimise resource use efficiency. Indeed, previous studies have emphasised matched plant height and maturation timing for optimal mixed cropping performance [@demie2022]. Additionally, the observed site and year effects, likely driven by climatic differences and soil type variability, highlight the necessity to investigate soil-plant interactions onto mixed cropping systems more closely. Thus, future efforts should focus on expanding predictive tools for mixed cropping suitability that facilitate the effective identification of the best-performing NLL-oat mixtures.

This study advances the understanding of under-explored quality parameters in mixed cropping, and connects quality to performance metrics by integrating the assessments of plant health, crop development, and productivity. Notably, several plant traits remained unaffected by mixed cropping, underscoring the potential for extrapolating findings across varieties and environments. Importantly, the findings reveal that the mixed cropping system exhibited greater resilience in terms of compensatory yield buffering and plant health compared with monoculture, highlighting its capacity to mitigate stress while maintaining productivity. The observed robust performance of oats in mixed stands, despite no added chemical fertiliser, further underscores the potential of mixed cropping as a viable strategy for sustainable intensification, particularly in organic systems, where chemical inputs are limited.

# CRediT authorship contribution statement
**Schlup Yannik**: Conceptualisation, investigation, data assembly, statistical analysis, methodology, project administration, resources, software, visualisation, writing, editing. **Lukas Graz**: Statistical analysis, methodology, software, visualisation, review. **Andreas Kaegi**: Conceptualisation, investigation, methodology, review. **Johan Six**: Conceptualisation, methodology, review. **Susanne Vogelgsang**: Conceptualisation, funding acquisition, methodology, project administration, review.

# Funding
This project was carried out within the Horizon 2020 funded project CROPDIVA (ID: 101000847). We gratefully acknowledge the financial support that made this study possible.

# Declaration of competing cnterest
The authors declare that they have no known personal relationships or competing financial interests that could have influenced the work reported in this paper.

# Declaration of generative AI and AI-assisted technologies in the writing process.
During the preparation of this work the authors used GPT-4 (OpenAI, California, USA) to improve the structure and efficiency of the code to render figures and GPT-o3pro (OpenAI, California, USA) in support of writing the abstract. After using this tool/service, the authors reviewed and edited the content as needed and take full responsibility for the created content.

# Data and analytical code
The repository, including the analytical code and data, is available at https://github.com/incorey/lupin-oat-mixed-cropping.

# Acknowledgments
We gratefully acknowledge the field technicians for their invaluable expertise in the cultivation of NLL and oats as well as the interns and MSc students for their great assistance in the field and laboratory work.

